from newspaper import Article
import nltk
nltk.download('punkt_tab')

urls = ['https://www.zacks.com/stock/news/2755934/the-zacks-analyst-blog-highlights-nvidia-coreweave-nebius-and-apple',
 'https://www.benzinga.com/news/legal/25/09/47823253/apple-settlement-ends-early-as-cfpb-scales-back-oversight',
 'https://www.benzinga.com/news/25/09/47822238/micron-to-test-ai-rally-after-nvidia-open-ai-deal-drove-ai-trade-higher-quantum-breakthrough-china-gold-move',
 'https://www.zacks.com/stock/news/2755893/zacks-investment-ideas-feature-highlights-nvidia-coreweave-nebius-apple-t-mobile-us-intel-and-crowdstrike',
 'https://www.benzinga.com/insights/news/25/09/47821419/investigating-apples-standing-in-technology-hardware-storage-amp-peripherals-industry-compared-to-c',
 'https://www.benzinga.com/etfs/broad-u-s-equity-etfs/25/09/47816223/how-to-trade-spy-top-tech-stocks-using-technical-analysis-26',
 'https://www.zacks.com/stock/news/2755466/tesla-tops-mag-7-group-in-a-month-etfs-in-focus',
 'https://www.benzinga.com/markets/tech/25/09/47814032/can-mediateks-new-chip-take-on-qualcomm',
 'https://www.zacks.com/stock/news/2755422/is-flexshares-morningstar-us-market-factor-tilt-etf-tilt-a-strong-etf-right-now',
 'https://www.zacks.com/stock/news/2755426/should-schwab-1000-index-etf-schk-be-on-your-investing-radar',
 'https://www.benzinga.com/markets/equities/25/09/47812582/stock-market-today-nasdaq-futures-rise-sp-500-slips-amid-mixed-trade-kenvue-micron-tech-nvidia-i',
 'https://www.fool.com/investing/2025/09/23/cls-stock-best-ai-stocks-to-buy-2025/',
 'https://www.fool.com/investing/2025/09/23/warren-buffett-sold-6-stocks-in-q2-heres-why-1-of/',
 'https://www.zacks.com/stock/news/2755403/company-news-for-sep-23-2025',
 'https://www.benzinga.com/markets/equities/25/09/47811827/us-stocks-extend-records-investor-sentiment-improves-fear-index-remains-in-greed-zone',
 'https://www.fool.com/investing/2025/09/23/nvidia-just-got-another-tailwind-why-groqs-69-bill/',
 'https://www.fool.com/investing/2025/09/23/warren-buffett-is-retiring-100-days-3-big-changes/',
 'https://www.zacks.com/stock/news/2755365/huge-ai-deals-keep-markets-at-record-highs',
 'https://www.benzinga.com/trading-ideas/long-ideas/25/09/47801356/apple-iphone-17-demand-could-exceed-expectations-gene-munster-says-upside-over-the-next-',
 'https://www.zacks.com/commentary/2755275/what-to-know-in-tech-iphone-sales-deliver-ai-dominates',
 'https://www.benzinga.com/markets/equities/25/09/47800416/markets-today-wall-street-monday-gold-nvidia',
 'https://www.zacks.com/stock/news/2755253/strength-seen-in-apple-aapl-can-its-32-jump-turn-into-more-strength',
 'https://www.fool.com/investing/2025/09/22/why-apple-stock-just-popped/',
 'https://www.benzinga.com/analyst-stock-ratings/analyst-color/25/09/47795934/apple-stock-has-more-upside-analyst-says-the-street-is-clearly-underestimatin',
 'https://www.benzinga.com/general/market-summary/25/09/47791611/prudent-investors-concerned-about-extreme-euphoria-represented-by-oklo-rally-and-impact-of',
 'https://www.benzinga.com/insights/news/25/09/47790550/competitor-analysis-evaluating-apple-and-competitors-in-technology-hardware-storage-amp-peripherals',
 'https://www.fool.com/investing/2025/09/22/apples-new-iphones-and-oracles-ai-bounce/',
 'https://www.benzinga.com/markets/tech/25/09/47787869/taiwan-semiconductor-mediatek-discuss-plans-to-develop-next-gen-chips-on-us-soil',
 'https://www.zacks.com/stock/news/2754686/apple-inc-aapl-is-attracting-investor-attention-here-is-what-you-should-know',
 'https://www.benzinga.com/markets/equities/25/09/47787188/how-to-trade-spy-top-tech-stocks-using-technical-analysis',
 'https://www.benzinga.com/news/politics/25/09/47784490/will-elon-musk-join-trump-administration-this-year-heres-what-betting-markets-are-predicting',
 'https://www.zacks.com/stock/news/2754548/should-ishares-russell-1000-etf-iwb-be-on-your-investing-radar',
 'https://www.zacks.com/stock/news/2754560/is-schwab-fundamental-us-large-company-etf-fndx-a-strong-etf-right-now',
 'https://www.benzinga.com/markets/equities/25/09/47783091/stock-market-today-dow-nasdaq-100-futures-slip-after-a-stellar-week-fox-oracle-dell-in-focus-on-',
 'https://www.benzinga.com/markets/equities/25/09/47782260/dow-hits-record-high-as-fed-cuts-rates-investor-sentiment-improves-fear-index-remains-in-greed-z',
 'https://www.fool.com/investing/2025/09/22/prediction-alphabet-4th-3-trillion-club-not-pltr/',
 'https://www.benzinga.com/markets/tech/25/09/47781206/wedbushs-dan-ives-hikes-apple-price-target-to-310-says-iphone-17-demand-tracking-10-15-ahead-of-ipho',
 'https://www.fool.com/investing/2025/09/21/3-warren-buffett-stocks-to-buy-hand-over-fist-and/',
 'https://www.benzinga.com/markets/tech/25/09/47779707/apples-iphone-17-pro-sparks-renewed-interest-despite-ai-challenges',
 'https://www.fool.com/investing/2025/09/21/4-ways-tsmc-makes-its-money/',
 'https://www.benzinga.com/markets/tech/25/09/47779480/steve-jobs-once-paused-for-18-seconds-to-answer-a-students-simple-question-here-is-what-the-apple-co',
 'https://www.benzinga.com/markets/tech/25/09/47779360/consumer-tech-news-sep-15-sep-19-fed-rate-cut-lifts-wall-street-to-records-as-meta-unveils-smart-gla',
 'https://www.benzinga.com/markets/tech/25/09/47779273/apples-iphone-17-series-takes-off-metas-new-smart-glasses-and-major-partnerships-in-ai-space-this-we',
 'https://www.fool.com/investing/2025/09/21/best-stock-to-buy-right-now-apple-vs-amazon/',
 'https://www.fool.com/investing/2025/09/21/why-i-think-dominos-pizza-dpz-is-a-warren/',
 'https://www.fool.com/investing/2025/09/21/the-best-warren-buffett-stocks-to-buy-with-3000-ri/',
 'https://www.fool.com/investing/2025/09/21/3-stocks-that-cut-you-a-check-each-month/',
 'https://www.benzinga.com/markets/tech/25/09/47778743/apples-iphone-17-surfaces-in-moscow-stores-despite-official-sales-ban',
 'https://www.benzinga.com/news/politics/25/09/47778633/trumps-h-1b-visa-plan-stuns-big-tech-white-house-says-100000-fee-is-one-time-only',
 'https://www.benzinga.com/markets/tech/25/09/47777943/how-ride-hailing-platforms-could-be-the-real-winners-of-the-autonomous-driving-push',
 'https://www.globenewswire.com/news-release/2025/09/23/3155077/14450/en/Micron-Technology-Inc-Reports-Results-for-the-Fourth-Quarter-and-Full-Year-of-Fiscal-2025.html',
 'https://www.benzinga.com/pressreleases/25/09/g47829657/cytokinetics-to-present-at-the-stifel-2025-virtual-cardiometabolic-forum',
 'https://www.benzinga.com/pressreleases/25/09/n47827788/melanie-hohman-to-head-up-pra-production-services',
 'https://cointelegraph.com/news/bitcoin-hit-1m-2035-bitwise-matt-hougan-thesis',
 'https://www.benzinga.com/pressreleases/25/09/n47826461/everi-announces-new-breeders-cup-mobile-app-on-beon-venue-platform-for-seamless-fan-experience',
 'https://www.benzinga.com/pressreleases/25/09/g47826238/eld-asset-management-oracles-ai-surge-boosts-stock',
 'https://www.zacks.com/stock/news/2755937/snow-expands-in-cloud-analytics-is-the-growth-thesis-strengthening',
 'https://www.benzinga.com/pressreleases/25/09/g47824893/ai-native-e-commerce-platform-genstore-secures-10-million-in-seed-funding',
 'https://www.zacks.com/stock/news/2755886/heres-why-semiconductor-etfs-are-hitting-52-week-highs',
 'https://www.zacks.com/stock/news/2755894/lumen-expands-multi-billion-ai-network-amid-surging-demand',
 'https://www.benzinga.com/news/topics/25/09/47823276/vibranium-labs-raises-4-6m-to-fix-vibe-coding-failures-with-ai-agents-after-engineers-admit-these-app',
 'https://www.benzinga.com/pressreleases/25/09/n47823242/smirnoff-and-troye-sivan-drop-new-business-update-from-vibes-hq-kicking-off-briefcase-drop-scaveng',
 'https://www.zacks.com/stock/news/2755924/the-zacks-analyst-blog-highlights-micron-technology-alphabet-meta-platforms-amazoncom-nvidia-and-advanced-micro-devices',
 'https://www.benzinga.com/pressreleases/25/09/g47820948/goguardian-launches-merge-classrooms-streamlining-classroom-management-for-educators',
 'https://www.benzinga.com/pressreleases/25/09/g47820819/remedys-nutrition-launches-advanced-herbal-parasite-cleanse-formula-to-support-natural-digestive-w',
 'https://www.benzinga.com/pressreleases/25/09/n47820005/new-tvo-series-the-premier-files-goes-behind-the-scenes-of-queens-park',
 'https://www.zacks.com/stock/news/2755723/pre-markets-flat-following-ai-tech-boost',
 'https://www.benzinga.com/pressreleases/25/09/g47819395/mcny-announces-41st-annual-silver-apple-honorees-five-marketing-leaders-and-one-corporation',
 'https://www.benzinga.com/pressreleases/25/09/g47818893/qualifacts-becomes-the-first-ehr-solutions-provider-to-earn-ai-management-systems-certification-is',
 'https://www.zacks.com/stock/news/2755592/why-alphabet-googl-is-a-top-stock-for-the-long-term',
 'https://cointelegraph.com/news/decentralized-detection-deepfake-crisis',
 'https://www.benzinga.com/m-a/25/09/47817277/why-hitachi-just-bought-this-ai-firm',
 'https://www.benzinga.com/news/legal/25/09/47816623/google-fights-antitrust-trial-to-avoid-ad-tech-breakup-too-great-a-risk-says-doj',
 'https://www.globenewswire.com/news-release/2025/09/23/3154794/0/en/Worksport-WKSP-Corporate-Update-Record-Margins-Strategic-Expansion-Imminent-Product-Launch.html',
 'https://www.benzinga.com/pressreleases/25/09/n47816305/extreme-music-launches-first-of-its-kind-production-music-panel-for-avid-media-composer',
 'https://www.benzinga.com/markets/tech/25/09/47816142/nvidia-gives-nvidia-gets-nvidia-grows-jensen-huangs-100-billion-brainwave',
 'https://www.benzinga.com/pressreleases/25/09/g47815878/aras-positioned-as-a-leader-and-ace-performer-in-the-2025-spark-matrix-product-lifecycle-managemen',
 'https://www.benzinga.com/pressreleases/25/09/g47815612/ecolomondo-delivers-growing-revenues-from-its-hawkesbury-tdp-facility',
 'https://www.benzinga.com/pressreleases/25/09/g47815634/bitget-wallet-hosts-morph-unity-airdrop-distributing-270-000-bgb',
 'https://www.globenewswire.com/news-release/2025/09/23/3154568/0/en/MariMed-s-Betty-s-Eddies-Spreads-Importance-of-Cancer-Screening-Education-and-Awareness-through-Partnership-with-Keep-A-Breast-Foundation.html',
 'https://cointelegraph.com/news/fnality-raises-136m-to-expand-blockchain-payment-network',
 'https://www.benzinga.com/pressreleases/25/09/n47814071/tech-mahindra-global-chess-league-partners-with-google-cloud-to-elevate-fan-experience-with-real-t',
 'https://www.fool.com/investing/2025/09/23/what-is-one-of-the-best-artificial-intelligence-ai/',
 'https://www.zacks.com/stock/news/2755433/is-vaneck-morningstar-wide-moat-etf-moat-a-strong-etf-right-now',
 'https://www.globenewswire.com/news-release/2025/09/23/3154513/0/en/Comstock-to-Participate-in-the-Lytham-Partners-Fall-2025-Investor-Conference-on-September-30-2025.html',
 'https://www.benzinga.com/pressreleases/25/09/g47813132/comstock-to-participate-in-the-lytham-partners-fall-2025-investor-conference-on-september-30-2025',
 'https://www.benzinga.com/pressreleases/25/09/g47812785/jackaroo-kings-saudi-national-day-special-event-secures-feature-on-middle-eastern-app-store',
 'https://www.benzinga.com/pressreleases/25/09/g47812779/cavitation-technologies-inc-announces-appointment-of-anton-glotser-as-vp-of-blockchain-infrastruct',
 'https://www.fool.com/investing/2025/09/23/next-decade-winner-cloud-stocks-monster-return/',
 'https://www.fool.com/investing/2025/09/23/ai-market-could-soar-over-6-times-by-2030-2-brilli/',
 'https://www.benzinga.com/news/politics/25/09/47812018/trumps-h1b-visa-fee-is-purely-destructive-warns-economist-paul-krugman-knocking-away-pillar-support',
 'https://www.fool.com/investing/2025/09/23/prediction-alphabets-ai-advances-could-add-3-trill/',
 'https://www.benzinga.com/pressreleases/25/09/g47809924/cytokinetics-shareholder-alert-by-former-louisiana-attorney-general-kahn-swick-foti-llc-reminds-in',
 'https://www.benzinga.com/pressreleases/25/09/g47809921/kbr-shareholder-alert-by-former-louisiana-attorney-general-kahn-swick-foti-llc-reminds-investors-w',
 'https://decrypt.co/340807/coinbase-100-million-bitcoin-backed-credit-miner-cleanspark',
 'https://www.benzinga.com/pressreleases/25/09/g47808840/apek-corporation-advances-government-ai-through-agentic-workflows-and-multi-agent-orchestration-pl',
 'https://www.benzinga.com/pressreleases/25/09/n47806924/itoolab-watracker-release-track-whatsapp-last-seen-status-in-real-time',
 'https://www.zacks.com/stock/news/2755960/palantir-vs-uipath-which-ai-first-software-stock-is-a-better-buy',
 'https://www.benzinga.com/pressreleases/25/09/n47823496/stegra-announces-agreement-with-microsoft-driving-demand-for-near-zero-emission-steel',
 'https://www.benzinga.com/insights/news/25/09/47821331/comparative-study-microsoft-and-industry-competitors-in-software-industry',
 'https://www.zacks.com/stock/news/2755734/zooms-global-expansion-picks-up-a-sign-of-more-upside',
 'https://www.benzinga.com/markets/macro-economic-events/25/09/47817498/jamie-dimon-says-trumps-h-1b-move-caught-him-off-guard-backs-merit-based-immigratio',
 'https://www.benzinga.com/pressreleases/25/09/g47817287/network-api-market-surges-to-6-13-billion-by-2030-dominated-by-ericsson-sweden-nokia-finland-cisco',
 'https://www.zacks.com/stock/news/2755559/crms-ai-and-data-cloud-arr-surges-120-can-the-momentum-continue',
 'https://www.zacks.com/stock/news/2755550/can-celestica-maintain-healthy-revenue-growth-with-an-ai-focus',
 'https://www.benzinga.com/pressreleases/25/09/n47816422/lanzajet-and-kazmunaygas-kmg-announce-kazakhstans-first-sustainable-aviation-fuel-project-passes-m',
 'https://www.fool.com/investing/2025/09/23/are-you-missing-out-on-the-top-performing-ai-etf/',
 'https://www.zacks.com/stock/news/2755499/3-stocks-to-boost-your-portfolio-as-sp-500-rally-gathers-steam',
 'https://www.zacks.com/stock/news/2755420/should-spdr-portfolio-sp-500-growth-etf-spyg-be-on-your-investing-radar',
 'https://www.fool.com/investing/2025/09/23/2-reasons-buy-amazon-stock-like-no-tomorrow/',
 'https://www.zacks.com/stock/news/2755413/fed-signals-more-easing-can-sp-500-etfs-rally-further',
 'https://www.fool.com/investing/2025/09/23/where-will-constellation-energy-be-in-5-years/',
 'https://www.benzinga.com/news/health-care/25/09/47811728/bill-gates-says-he-rfk-jr-agree-to-disagree-on-vaccines-but-still-plan-to-work-together',
 'https://www.scmp.com/tech/tech-trends/article/3326510/ai-industry-faces-us800-billion-revenue-shortfall-amid-data-centre-expansion-bain',
 'https://decrypt.co/340794/nvidia-100-billion-openai-historic-ai-infrastructure-deal-stock-pops',
 'https://www.benzinga.com/markets/tech/25/09/47799220/what-is-going-on-with-nvidia-stock-on-monday',
 'https://www.zacks.com/stock/news/2755230/alibaba-clouds-ai-boom-can-this-momentum-drive-even-higher-growth',
 'https://www.fool.com/investing/2025/09/22/media-merger-mania-strikes-again/',
 'https://www.fool.com/investing/2025/09/22/2-top-artificial-intelligence-ai-stocks-ready-for/',
 'https://www.cnbc.com/2025/09/22/nvidia-openai-data-center.html',
 'https://www.zacks.com/stock/news/2755136/mdb-shares-jump-39-ytd-should-you-add-the-stock-to-your-portfolio',
 'https://www.zacks.com/stock/news/2755187/c3ais-q1-margin-squeeze-raises-questions-on-path-to-profitability',
 'https://www.zacks.com/stock/news/2755029/ericsson-wins-sek-125b-vodafonethree-deal-to-build-uks-5g-network',
 'https://www.benzinga.com/insights/news/25/09/47790490/understanding-microsofts-position-in-software-industry-compared-to-competitors',
 'https://www.fool.com/investing/2025/09/22/invest-in-quantum-computing-stocks-great-buys/',
 'https://www.zacks.com/stock/news/2754916/the-zacks-analyst-blog-highlights-oracle-and-microsoft',
 'https://www.benzinga.com/pressreleases/25/09/n47786767/solutions-2-go-inc-and-io-interactive-announce-global-launch-of-007-first-light',
 'https://www.benzinga.com/markets/tech/25/09/47786572/amazon-alphabet-meta-other-big-tech-stocks-fall-in-monday-pre-market-whats-going-on',
 'https://www.zacks.com/stock/news/2754755/zacks-investment-ideas-feature-highlights-iwm-credo-technology-and-ionq',
 'https://www.fool.com/investing/2025/09/22/3-no-brainer-warren-buffett-stocks-to-buy-now/',
 'https://www.benzinga.com/Opinion/25/09/47829071/fed-chairs-no-risk-free-path-warning-sparks-unusual-outcome-as-gold-and-stocks-hit-records-simultaneously',
 'https://www.benzinga.com/analyst-stock-ratings/reiteration/25/09/47828385/what-will-nvidias-100-billion-openai-investment-reap',
 'https://www.zacks.com/stock/news/2755962/is-now-the-time-to-buy-small-cap-stocks',
 'https://www.benzinga.com/markets/equities/25/09/47826628/us-stock-market-outlook-analysis-1929-dot-com-euphoria-crash',
 'https://www.fool.com/investing/2025/09/23/is-reddit-stock-an-nvidia-level-winner/',
 'https://www.zacks.com/commentary/2755944/skin-in-the-game-the-us-government-nvidia-back-intel',
 'https://www.benzinga.com/trading-ideas/movers/25/09/47824304/nvidia-high-fives-palantir-rocket-lab-on-this-list-of-10-bagger-legends',
 'https://www.benzinga.com/trading-ideas/movers/25/09/47822768/whats-going-on-with-coreweave-crwv-stock-tuesday',
 'https://www.zacks.com/stock/news/2755904/anet-rides-on-strength-in-cloud-networking-market-will-it-sustain',
 'https://www.zacks.com/stock/news/2755902/zacks-investment-ideas-feature-highlights-nvidia-and-palantir-technologies',
 'https://www.zacks.com/stock/news/2755882/halozyme-therapeutics-and-synopsys-have-been-highlighted-as-zacks-bull-and-bear-of-the-day',
 'https://www.zacks.com/stock/news/2755774/can-an-expanding-clientele-push-wulf-stocks-top-line-growth',
 'https://www.benzinga.com/insights/news/25/09/47821318/analyzing-nvidia-in-comparison-to-competitors-in-semiconductors-amp-semiconductor-equipment-industr',
 'https://www.zacks.com/stock/news/2755748/pre-markets-flat-after-record-high-level',
 'https://www.benzinga.com/trading-ideas/movers/25/09/47820311/iren-stock-is-trending-tuesday-whats-going-on',
 'https://www.zacks.com/stock/news/2755688/heres-why-nvidia-nvda-is-a-strong-momentum-stock',
 'https://www.benzinga.com/markets/tech/25/09/47817979/super-micro-nvidia-power-lambdas-zero-emission-data-center-ai-training',
 'https://www.zacks.com/stock/news/2755601/smci-rises-64-in-a-month-should-you-buy-sell-or-hold-the-stock',
 'https://www.zacks.com/stock/news/2755561/nvidias-networking-revenues-double-can-it-keep-the-momentum',
 'https://www.zacks.com/stock/news/2755530/is-most-watched-stock-nvidia-corporation-nvda-worth-betting-on-now',
 'https://www.benzinga.com/markets/equities/25/09/47815933/nvidia-supplier-asml-soars-in-quality-rankings-as-bofa-sees-it-winning-big-from-5-billion-intel-',
 'https://www.benzinga.com/pressreleases/25/09/n47815910/ehs-issues-public-shareholder-letter-and-presentation-to-the-board-of-trueblue',
 'https://www.benzinga.com/markets/tech/25/09/47814412/huawei-bets-on-brute-force-to-outpace-nvidia',
 'https://www.benzinga.com/markets/equities/25/09/47813976/short-seller-jim-chanos-scrutinizes-jensen-huang-led-nvidias-ai-factory-cost-estimates-well-abov',
 'https://www.zacks.com/commentary/2755292/bear-of-the-day-synopsys-snps',
 'https://www.fool.com/investing/2025/09/23/1-reason-why-buy-nvidia-stock-before-end-2025/',
 'https://www.fool.com/investing/2025/09/23/is-bigbearai-a-millionaire-maker-stock/',
 'https://www.fool.com/investing/2025/09/23/intel-could-kill-this-business-thanks-to-the-nvidi/',
 'https://www.fool.com/investing/2025/09/23/best-bargain-artificial-intelligence-ai-stock-buy/',
 'https://www.zacks.com/stock/news/2755890/nissans-next-gen-propilot-demo-global-av-race-heating-up',
 'https://www.benzinga.com/analyst-stock-ratings/price-target/25/09/47822585/tesla-to-rally-around-4-here-are-10-top-analyst-forecasts-for-tuesday',
 'https://www.fool.com/investing/2025/09/23/whats-going-on-with-tesla-stock/',
 'https://www.fool.com/investing/2025/09/23/better-ev-stock-rivian-vs-tesla/',
 'https://www.benzinga.com/markets/tech/25/09/47812583/tesla-records-17-3k-insured-registrations-in-china-during-3rd-week-of-september-sales-grow-over-33',
 'https://www.benzinga.com/markets/asia/25/09/47812494/teslas-chinese-rival-looks-all-set-to-soar-amid-strong-domestic-ev-tailwinds-momentum-score-surges',
 'https://www.fool.com/investing/2025/09/23/maybe-lucid-was-right-all-along-bad-news-for-truck/',
 'https://www.benzinga.com/markets/tech/25/09/47812065/tesla-urges-shareholders-to-vote-in-favor-of-1-trillion-ceo-compensation-package-for-elon-musk',
 'https://www.fool.com/investing/2025/09/23/the-smartest-artificial-intelligence-etf-to-buy-wi/',
 'https://www.benzinga.com/markets/tech/25/09/47811199/tesla-sued-by-multiple-owners-in-china-for-failing-to-deliver-fsd-elon-musk-claimed-that',
 'https://www.benzinga.com/markets/tech/25/09/47810403/elon-musk-led-teslas-san-francisco-ride-hailing-expansion-alarmed-officials-report',
 'https://www.benzinga.com/crypto/cryptocurrency/25/09/47810165/dan-ives-compares-sam-altmans-world-network-to-tesla-nvidia-palantir-in-their-infancy-an-ai',
 'https://www.fool.com/investing/2025/09/22/bill-gurley-one-of-ubers-earliest-investors-just-d/',
 'https://www.benzinga.com/markets/tech/25/09/47808468/tesla-model-y-fails-teens-road-test-marked-out-of-order-mid-exam',
 'https://www.zacks.com/stock/news/2755313/tesla-tsla-laps-the-stock-market-heres-why',
 'https://decrypt.co/340762/humanoid-robot-cheaper-rivals-full-security-flaws-researchers',
 'https://www.fool.com/investing/2025/09/22/a-rule-breaker-investing-highlight-reel/',
 'https://www.benzinga.com/analyst-stock-ratings/reiteration/25/09/47792372/tesla-aims-for-record-deliveries-ai-and-self-driving-edge-over-rivals-analyst',
 'https://www.benzinga.com/insights/news/25/09/47789170/if-you-invested-100-in-tesla-stock-10-years-ago-you-would-have-this-much-today',
 'https://www.fool.com/investing/2025/09/22/the-motley-fool-interviews-tom-slater-head-of-us-e/',
 'https://www.zacks.com/stock/news/2754661/how-teslas-robotaxi-service-looks-3-months-after-launch',
 'https://www.benzinga.com/markets/tech/25/09/47784833/tesla-poised-for-16-upside-piper-sandler-says-after-china-visit',
 'https://www.benzinga.com/pressreleases/25/09/g47784517/slp-securities-news-why-did-simulations-plus-inc-stock-drop-26-investors-with-losses-reminded-to-c',
 'https://www.benzinga.com/pressreleases/25/09/g47784463/line-securities-news-why-did-lineage-inc-stock-drop-17-investors-with-losses-reminded-to-contact-b',
 'https://www.benzinga.com/pressreleases/25/09/g47784443/jhx-securities-news-why-did-james-hardie-industries-plc-stock-drop-34-investors-with-losses-remind',
 'https://www.benzinga.com/pressreleases/25/09/g47784429/brbr-securities-news-why-did-bellring-brands-stock-drop-18-investors-with-losses-reminded-to-conta',
 'https://www.benzinga.com/markets/tech/25/09/47783018/tesla-says-you-can-avail-ev-credit-even-if-you-take-delivery-after-september-30-deadline-heres-how',
 'https://www.benzinga.com/markets/tech/25/09/47782201/warren-buffetts-berkshire-hathaway-exits-byd-position-after-17-years-ending-charlie-munger-backed-be',
 'https://www.fool.com/investing/2025/09/22/industrials-hot-ticker-stock-continues-to-climb-bu/',
 'https://www.benzinga.com/markets/tech/25/09/47781698/ross-gerber-says-teslas-fsd-cannot-be-called-self-driving-due-to-lack-of-necessary-safety-as-influen',
 'https://www.scmp.com/business/china-business/article/3326359/warren-buffetts-berkshire-hathaway-wraps-17-year-investment-chinese-ev-maker-byd',
 'https://www.benzinga.com/markets/tech/25/09/47781225/trump-elon-musk-reunite-for-the-1st-time-in-months-at-charlie-kirks-memorial-what-this-could-mean-fo',
 'https://www.fool.com/investing/2025/09/21/my-top-growth-stock-to-buy-for-year-and-its-not-ev/',
 'https://www.fool.com/investing/2025/09/21/3-ways-tesla-stock-could-surprise-everyone-and-soa/',
 'https://cointelegraph.com/news/traditional-economies-sunset-favor-internet',
 'https://www.fool.com/investing/2025/09/21/electric-vehicle-manufacturer-byd-cuts-out-the-mid/',
 'https://www.fool.com/investing/2025/09/21/what-is-one-of-the-best-ev-stocks-to-buy-right-now/']

seen = set()
unique_urls = []
for u in urls:
    if u not in seen:
        seen.add(u)
        unique_urls.append(u)

summaries = []

for url in unique_urls: 
    try: 
        news = Article(url)
        news.download()
        news.parse()
        news.nlp()
        if news.summary:
             summaries.append(news.summary)
    except Exception as e: #add exemption for urls that get bad 401 error 
        print(f"Error processing url {url} {e}")

out_path = "news_summary.txt"
with open(out_path, "w", encoding="utf-8") as f:
    for s in summaries:
        f.write(s.replace("\n", " ") + "\n")

print(f"wrote {len(summaries)} summaries to {out_path}")



         