from newspaper import Article
import nltk
nltk.download('punkt_tab')

urls = ['https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-drift-higher-as-wall-street-weighs-feds-next-move-232914987.html',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-drift-as-wall-street-braces-for-revision-to-jobs-data-232914335.html',
 'https://applech2.com/archives/20250909-belkin-boostcharge-pro-3-ports-70w.html',
 'https://applech2.com/archives/20250909-google-drive-114-ends-support-macos-11-big-sur.html',
 'https://biztoc.com/x/980e4c510f4a1bd3',
 'https://www.barchart.com/story/news/34666920/stocks-mostly-higher-on-fed-easing-prospects',
 'https://www.marketwatch.com/story/these-are-the-stock-market-trades-to-make-going-into-the-end-of-the-year-according-to-goldman-sachs-694bfedf',
 'https://finance.yahoo.com/video/inflation-watch-apple-event-p-131510114.html',
 'https://www.barchart.com/story/news/34660103/stocks-set-to-open-higher-as-fed-rate-cut-expectations-rise-u-s-inflation-data-awaited',
 'https://www.etfdailynews.com/2025/09/08/apple-inc-aapl-is-lcnb-corps-7th-largest-position/',
 'https://www.etfdailynews.com/2025/09/08/first-western-trust-bank-has-24-90-million-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/condor-capital-management-has-30-93-million-holdings-in-apple-inc-aapl/',
 'https://wccftech.com/apple-watch-ultra-3-support-5g-and-satellite-connectivity-thanks-to-mediatek-modems/',
 'https://www.etfdailynews.com/2025/09/08/riverpark-capital-management-llc-purchases-231-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/connor-clark-lunn-investment-management-ltd-acquires-110777-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/avant-capital-llc-has-1-06-million-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/founders-financial-alliance-llc-reduces-stock-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/fsa-wealth-partners-inc-invests-479000-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/truepoint-inc-purchases-6612-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/ardent-capital-management-inc-raises-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/integrity-financial-corp-wa-has-7-50-million-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/brookmont-capital-management-has-214000-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/promising-technology-stocks-to-add-to-your-watchlist-september-6th/',
 'https://finance.yahoo.com/news/why-td-cowen-stays-bullish-040345920.html',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-climb-to-records-as-sharp-jobs-revision-sets-stage-for-inflation-data-200028949.html',
 'https://biztoc.com/x/50bf0fc00ff95bc0',
 'https://biztoc.com/x/99f7b857d70760a5',
 'https://applech2.com/archives/20250910-macos-26-tahoe-and-ios-26-available-9-15.html',
 'https://finance.yahoo.com/news/apple-debuts-superthin-iphone-air-alongside-iphone-17-and-iphone-17-pro-181527722.html',
 'https://economictimes.indiatimes.com/news/international/us/apple-stock-slips-after-awe-dropping-iphone-17-event-as-wall-street-unimpressed-with-incremental-upgrades/articleshow/123792119.cms',
 'https://biztoc.com/x/842b3b9072f9515d',
 'https://finance.yahoo.com/news/apple-reveals-apple-watch-series-11-and-ultra-3-with-hypertension-detection-improved-durability-174053517.html',
 'https://finance.yahoo.com/news/apple-debuts-airpods-pro-3-with-improved-audio-and-built-in-heart-rate-tracking-171606113.html',
 'https://economictimes.indiatimes.com/news/international/us/us-stock-market-today-reverses-gains-after-us-jobs-data-is-revised-sharply-down-dow-rises-while-sp-500-and-nasdaq-slip-from-record-highs-as-apple-iphone-17-event-stirs-investor-focus/articleshow/123789052.cms',
 'https://www.thestreet.com/markets/stock-market-today-september-9-2025',
 'https://www.barchart.com/story/news/34695367/alphabet-stock-is-goog-outperforming-the-communication-services-sector',
 'https://finance.yahoo.com/news/market-minute-9-9-25-141500334.html',
 'https://www.marketwatch.com/story/why-jpmorgan-is-warning-the-fed-rate-cut-everyone-expects-could-sink-stocks-0179698d',
 'https://macdailynews.com/2025/09/09/macdailynews-presents-live-coverage-of-apples-awe-dropping-special-event/',
 'https://biztoc.com/x/53996170a27a52a6',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-waver-after-us-jobs-data-is-revised-sharply-down-133638637.html',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-nudge-up-as-wall-street-braces-for-revision-to-jobs-data-232914330.html',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-edge-up-after-us-jobs-data-is-revised-sharply-down-133638948.html',
 'https://economictimes.indiatimes.com/news/international/us/apple-iphone-17-series-launch-event-today-faces-criticism-daniel-newman-even-before-its-products-are-launched/articleshow/123786975.cms',
 'https://biztoc.com/x/54120db86c94c990',
 'https://biztoc.com/x/f624aca537f4d511',
 'https://economictimes.indiatimes.com/news/international/us/us-stock-market-futures-rise-as-nasdaq-hits-record-sp-500-and-dow-climb-fed-rate-cut-bets-build-while-apples-iphone-17-event-takes-center-stage-with-oracle-and-gamestop-earnings-in-focus/articleshow/123784419.cms',
 'https://www.etfdailynews.com/2025/09/09/covington-investment-advisors-inc-has-30-27-million-stock-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/09/blueprint-investment-partners-llc-cuts-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/09/virtu-financial-llc-sells-4792-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/09/apple-inc-aapl-stock-holdings-boosted-by-robinson-smith-wealth-advisors-llc/',
 'https://www.etfdailynews.com/2025/09/09/direxion-daily-aapl-bull-2x-shares-nasdaqaapu-shares-down-1-4-time-to-sell/',
 'https://www.fool.com.au/2025/09/09/3-exciting-asx-etfs-to-buy-with-1000-this-month/',
 'https://www.etfdailynews.com/2025/09/09/apple-inc-aapl-is-sierra-summit-advisors-llcs-largest-position/',
 'https://www.etfdailynews.com/2025/09/09/stonebridge-capital-management-inc-sells-4100-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/09/apple-inc-aapl-is-manhattan-west-asset-management-llcs-3rd-largest-position/',
 'https://www.etfdailynews.com/2025/09/09/apple-inc-aapl-shares-sold-by-atlas-capital-advisors-inc/',
 'https://www.etfdailynews.com/2025/09/09/apple-inc-aapl-shares-acquired-by-true-north-advisors-llc/',
 'https://www.etfdailynews.com/2025/09/09/johnson-financial-group-llc-has-4-32-million-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/09/promising-retail-stocks-to-add-to-your-watchlist-september-7th/',
 'https://mjtsai.com/blog/2025/09/08/android-tracking-switch-privacy-lawsuit/',
 'https://podcasts.apple.com/us/podcast/passing-go-sharing-data-google-avoids-breakup-but-must/id1401725029?i=1000725507217',
 'https://finance.yahoo.com/news/why-rocket-lab-rklb-stock-182639864.html',
 'https://finance.yahoo.com/news/why-soundhound-ai-soun-stock-182613993.html',
 'https://finance.yahoo.com/news/live/stock-market-today-sp-500-rises-nasdaq-on-track-for-record-as-wall-street-looks-ahead-to-inflation-reality-check-170830778.html',
 'https://economictimes.indiatimes.com/news/international/us/us-stock-market-surges-today-nasdaq-and-sp-500-hit-record-highs-dow-flat-wall-street-on-the-move-as-robinhood-and-applovin-stocks-soar/articleshow/123768912.cms',
 'https://www.forbes.com/sites/greatspeculations/2025/09/08/buy-sell-or-hold-american-eagle-stock/',
 'https://biztoc.com/x/f641c289149dcfc7',
 'https://biztoc.com/x/a451abb732892338',
 'https://www.forbes.com/sites/greatspeculations/2025/09/08/how-will-synopsys-stock-react-to-its-upcoming-earnings/',
 'https://www.forbes.com/sites/greatspeculations/2025/09/08/does-shopify-stock-have-more-room-to-run/',
 'https://biztoc.com/x/5d2cd09fad7d0633',
 'https://finance.yahoo.com/news/live/stock-market-today-sp-500-nasdaq-dow-rise-as-wall-street-looks-ahead-to-inflation-reality-check-000205760.html',
 'https://finance.yahoo.com/news/pinterest-ceo-ai-is-winning-over-gen-z--but-growth-isnt-guaranteed-222201168.html',
 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_790d11f5-514d-410c-b5f2-791e94252c87',
 'https://finance.yahoo.com/news/oracle-stock-soars-after-ceo-says-ai-fueled-cloud-revenue-set-to-jump-to-144-billion-154530523.html',
 'https://finance.yahoo.com/news/oracle-stock-soars-after-ceo-says-ai-fueled-cloud-revenue-set-to-soar-to-144-billion-154530807.html',
 'https://www.barchart.com/story/news/34696846/dear-oracle-stock-fans-mark-your-calendars-for-september-9',
 'https://biztoc.com/x/7d32562619b02401',
 'https://www.forbes.com/sites/greatspeculations/2025/09/09/a-weak-jobs-report-implies-lower-rates-ahead/',
 'https://biztoc.com/x/3da3196480da973a',
 'https://finance.yahoo.com/news/nebius-signs-17-4-billion-211147146.html',
 'https://biztoc.com/x/ef03408de9947638',
 'https://www.etfdailynews.com/2025/09/08/koss-olinger-consulting-llc-increases-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/cynosure-group-llc-has-3-42-million-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/zions-bancorporation-national-association-ut-invests-29-88-million-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-stake-cut-by-summit-financial-strategies-inc/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-shares-bought-by-rezny-wealth-management-inc/',
 'https://www.etfdailynews.com/2025/09/08/everett-harris-co-ca-has-565-11-million-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/nicholson-wealth-management-group-llc-raises-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/townsquare-capital-llc-buys-12649-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-holdings-lowered-by-nbw-capital-llc/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-is-locust-wood-capital-advisers-llcs-2nd-largest-position/',
 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_2d2b024f-927e-4e45-b490-fb5d68c8cd55',
 'https://biztoc.com/x/d654010efc36efe5',
 'https://www.coindesk.com/markets/2025/09/09/microsoft-s-usd17-4b-ai-bet-lifts-crypto-miners-as-bitcoin-slips',
 'https://www.forbes.com/sites/libertbarry/2025/09/09/the-best-and-worst-of-times-----ai-vs-saas-for-1-trillion-market/',
 'https://www.barchart.com/story/news/34699058/is-nebius-stock-a-buy-sell-or-hold-on-the-microsoft-ai-deal',
 'https://biztoc.com/x/eca60fef07acee96',
 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_d389609f-9d7a-4cab-8340-5dd659f41254',
 'https://www.investopedia.com/top-stock-movers-now-unitedhealth-group-fox-freeport-mcmoran-and-more-11806307',
 'https://www.investopedia.com/watch-these-nebius-price-levels-as-stock-surges-on-ai-deal-with-microsoft-11806125',
 'https://www.investopedia.com/nvidia-backed-nebius-stock-soars-50-percent-on-ai-infrastructure-deal-with-microsoft-11806153',
 'https://finance.yahoo.com/news/microsoft-msft-rose-q2-results-125318341.html',
 'https://biztoc.com/x/7d307e088e352e76',
 'https://biztoc.com/x/edbf84cfe64aae3b',
 'https://www.investopedia.com/5-things-to-know-before-the-stock-market-opens-september-9-2025-11806131',
 'https://biztoc.com/x/fe6d31adccc31cea',
 'https://biztoc.com/x/3cf55273f46ad182',
 'https://www.coindesk.com/markets/2025/09/09/nebius-microsoft-usd17-4b-deal-lifts-ai-mining-stocks-in-pre-market-trading',
 'https://www.etfdailynews.com/2025/09/09/polen-capital-management-llc-cuts-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/biltmore-family-office-llc-has-13-24-million-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/magellan-asset-management-ltd-has-624-98-million-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/microsoft-corporation-msft-shares-bought-by-white-lighthouse-investment-management-inc/',
 'https://www.etfdailynews.com/2025/09/09/avos-capital-management-llc-acquires-28-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/mizuho-markets-americas-llc-raises-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/invesco-ltd-raises-stock-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/direxion-daily-msft-bull-2x-shares-nasdaqmsfu-stock-price-up-1-3-whats-next/',
 'https://www.etfdailynews.com/2025/09/09/taylor-financial-group-inc-has-2-88-million-stock-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/fiduciary-family-office-llc-buys-18086-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/manhattan-west-asset-management-llc-purchases-5063-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/sierra-summit-advisors-llc-decreases-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/09/benjamin-edwards-inc-sells-18604-shares-of-microsoft-corporation-msft/',
 'https://biztoc.com/x/75129f9a0941420a',
 'https://biztoc.com/x/509fef805ecb4df8',
 'https://www.barchart.com/story/news/34671143/nvidias-rally-is-facing-a-reality-check-should-you-buy-nvda-stock-despite-citis-target-price-cut',
 'https://finance.yahoo.com/news/palantir-stock-breakout-170900343.html',
 'https://biztoc.com/x/57374d35224ac237',
 'https://finance.yahoo.com/news/jim-cramer-reveals-big-debate-152142815.html',
 'https://www.barchart.com/story/news/34668168/stocks-supported-by-hopes-of-fed-rate-cuts',
 'https://biztoc.com/x/3f873a54d800383e',
 'https://biztoc.com/x/b864544f67f45752',
 'https://finance.yahoo.com/news/alibaba-bytedance-others-remain-keen-142925517.html',
 'https://www.etfdailynews.com/2025/09/08/summit-financial-strategies-inc-decreases-stake-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/nvidia-corporation-nvda-shares-purchased-by-rezny-wealth-management-inc/',
 'https://www.etfdailynews.com/2025/09/08/forsta-ap-fonden-has-696-87-million-stake-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/bristlecone-advisors-llc-has-32-57-million-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/nvidia-corporation-nvda-is-ns-partners-ltds-2nd-largest-position/',
 'https://www.etfdailynews.com/2025/09/08/benjamin-edwards-inc-sells-157657-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/best-automotive-stocks-to-research-september-6th/',
 'https://www.etfdailynews.com/2025/09/08/manhattan-west-asset-management-llc-raises-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/measured-wealth-private-client-group-llc-sells-1700-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/frank-rimerman-advisors-llc-sells-25907-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/analysts-set-nvidia-corporation-nasdaqnvda-pt-at-207-69/',
 'https://www.thestreet.com/economy/inflation-is-the-weeks-watchword',
 'https://finance.yahoo.com/news/ubs-calls-nvidia-nvda-buy-035937618.html',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-falters-while-sp-500-nasdaq-eye-fresh-records-as-oracle-lifts-ai-hopes-233143978.html',
 'https://finance.yahoo.com/news/quantum-pact-nvidia-honeywell-raise-190000357.html',
 'https://finance.yahoo.com/news/sailpoint-ceo-ai-agents-promise-big-gains--and-big-risks-162015066.html',
 'https://biztoc.com/x/a98b2b10460176a2',
 'https://biztoc.com/x/9a6531dcb9b7fc3f',
 'https://www.barchart.com/story/news/34697384/this-red-light-for-nvda-hasnt-flashed-since-it-was-a-100-stock-but-this-3-1-option-strategy-could-be-an-escape-hatch',
 'https://www.thestreet.com/investing/analyst-surprisingly-cuts-nvidia-stock-target-amid-a-growing-threat',
 'https://www.globenewswire.com/news-release/2025/09/09/3147154/0/en/NVIDIA-Unveils-Rubin-CPX-A-New-Class-of-GPU-Designed-for-Massive-Context-Inference.html',
 'https://finance.yahoo.com/news/nvidia-debuts-rubin-cpx-gpu-for-massive-ai-applications-150047032.html',
 'https://finance.yahoo.com/news/nebius-shares-surge-17-4-145136091.html',
 'https://www.thestreet.com/technology/this-nvidia-backed-ai-stock-just-pulled-off-a-jaw-dropping-play-',
 'https://www.etfdailynews.com/2025/09/09/9143-shares-in-nvidia-corporation-nvda-acquired-by-johnson-financial-group-llc/',
 'https://www.etfdailynews.com/2025/09/09/invesco-ltd-has-14-38-billion-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/09/nvidia-corporation-nvda-shares-sold-by-aft-forsyth-company-inc/',
 'https://www.etfdailynews.com/2025/09/09/nvidia-corporation-nvda-shares-acquired-by-stonebridge-capital-management-inc/',
 'https://www.etfdailynews.com/2025/09/09/aveo-capital-partners-llc-has-2-37-million-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/09/king-luther-capital-management-corp-buys-32801-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/09/lockheed-martin-investment-management-co-purchases-149730-shares-of-nvidia-corporation-nvda/',
 'https://www.globenewswire.com/news-release/2025/09/08/3146456/3080/en/Lost-Money-on-Tesla-Inc-TSLA-Join-Class-Action-Suit-Seeking-Recovery-Contact-Levi-Korsinsky.html',
 'https://biztoc.com/x/6f2461e3d79ccc09',
 'https://www.thestreet.com/automotive/tesla-report-reveals-concerning-customer-behavior-',
 'https://biztoc.com/x/e620ca9ffa816d75',
 'https://biztoc.com/x/b3f54f787124bcf7',
 'https://biztoc.com/x/86669513beabac95',
 'https://biztoc.com/x/ff0640ebc0d139ac',
 'https://biztoc.com/x/698f0e05a229194f',
 'https://finance.yahoo.com/news/tesla-tsla-entry-india-sees-142931553.html',
 'http://electrek.co/2025/09/08/tesla-tsla-us-market-share-ev-market-drop-new-lows/',
 'https://biztoc.com/x/8c10aa4ae1b6e531',
 'https://economictimes.indiatimes.com/news/international/us/us-stock-futures-edge-higher-today-dow-sp-500-nasdaq-start-the-week-in-green-as-wall-street-bets-on-fed-cut-and-key-inflation-test/articleshow/123763670.cms',
 'https://www.etfdailynews.com/2025/09/08/tradr-2x-short-tsla-daily-etf-nasdaqtslq-short-interest-up-68-3-in-august/',
 'https://www.etfdailynews.com/2025/09/08/direxion-daily-tsla-bear-1x-shares-nasdaqtsls-short-interest-update/',
 'https://www.etfdailynews.com/2025/09/08/promising-energy-stocks-to-add-to-your-watchlist-september-6th/',
 'https://www.etfdailynews.com/2025/09/08/industrial-stocks-to-follow-now-september-6th/',
 'https://www.etfdailynews.com/2025/09/08/utility-stocks-to-keep-an-eye-on-september-6th/',
 'https://finance.yahoo.com/news/tesla-stock-nasdaq-tsla-faces-040724978.html',
 'https://biztoc.com/x/f46d198ba830a150',
 'https://www.barchart.com/story/news/34696776/teslas-market-share-just-plunged-to-a-2017-low-is-this-a-sign-to-ditch-tsla-stock-for-good',
 'https://www.etfdailynews.com/2025/09/09/graniteshares-1-25x-long-tsla-daily-etf-nasdaqtsl-short-interest-up-49-0-in-august/',
 'https://www.etfdailynews.com/2025/09/09/solar-stocks-worth-watching-september-7th/']
seen = set()
unique_urls = []
for u in urls:
    if u not in seen:
        seen.add(u)
        unique_urls.append(u)

summaries = []

for url in unique_urls: 
    try: 
        news = Article(url)
        news.download()
        news.parse()
        news.nlp()
        if news.summary:
             summaries.append(news.summary)
    except Exception as e: #add exemption for urls that get bad 401 error 
        print(f"Error processing url {url} {e}")

out_path = "news_summary.txt"
with open(out_path, "w", encoding="utf-8") as f:
    for s in summaries:
        f.write(s.replace("\n", " ") + "\n")

print(f"wrote {len(summaries)} summaries to {out_path}")



         