from newspaper import Article
import nltk
nltk.download('punkt_tab')

urls = ['https://biztoc.com/x/5d2cd09fad7d0633',
 'https://finance.yahoo.com/news/live/stock-market-today-sp-500-nasdaq-dow-rise-as-wall-street-looks-ahead-to-inflation-reality-check-000205760.html',
 'https://biztoc.com/x/6e87ca74579feecb',
 'https://www.etfdailynews.com/2025/09/06/metaverse-stocks-to-watch-today-september-4th/',
 'https://www.etfdailynews.com/2025/09/06/prairieview-partners-llc-reduces-stock-holdings-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/ritter-daniher-financial-advisory-llc-de-has-432000-holdings-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/nvidia-corporation-nvda-shares-purchased-by-westwood-holdings-group-inc/',
 'https://www.etfdailynews.com/2025/09/06/campbell-capital-management-inc-has-65000-stake-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/promising-technology-stocks-to-research-september-4th/',
 'https://www.forbes.com/sites/michaelfoster/2025/09/06/volatility-is-back-and-this-78-cef-is-here-to-get-us-through-it/',
 'https://finance.yahoo.com/news/nvidia-nvda-viewed-key-ai-100958624.html',
 'https://www.etfdailynews.com/2025/09/06/wealthshield-partners-llc-has-13-93-million-holdings-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/nvidia-corporation-nvda-shares-purchased-by-strategy-asset-managers-llc/',
 'https://www.etfdailynews.com/2025/09/06/palacios-wealth-management-llc-boosts-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/atlantic-private-wealth-llc-has-109000-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/bouchey-financial-group-ltd-has-2-80-million-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/nvidia-corporation-nvda-is-intrust-bank-nas-8th-largest-position/',
 'https://www.etfdailynews.com/2025/09/06/tidemark-llc-sells-90-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/06/rep-cleo-fields-purchases-shares-of-nvidia-corporation-nasdaqnvda-6/',
 'https://www.etfdailynews.com/2025/09/06/rep-cleo-fields-buys-nvidia-corporation-nasdaqnvda-shares-3/',
 'https://www.etfdailynews.com/2025/09/06/rep-cleo-fields-buys-nvidia-corporation-nasdaqnvda-stock-6/',
 'https://biztoc.com/x/28b4d83edb73ff69',
 'https://www.thestreet.com/technology/nvidias-new-investment-is-a-game-changer-for-quantum-stocks',
 'https://finance.yahoo.com/news/ubs-calls-nvidia-nvda-buy-035937618.html',
 'https://biztoc.com/x/1e28cdbd59dce6f1',
 'https://biztoc.com/x/27db10857f5a4fa9',
 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_6f5d77e4-9f88-4f3d-8991-25ca6fac0f85',
 'https://finance.yahoo.com/news/nvidia-denies-h100-h200-ai-135706413.html',
 'https://finance.yahoo.com/news/why-ai-stock-tremors-are-ripping-through-portfolios-123012040.html',
 'https://www.forbes.com/sites/bill_stone/2025/09/07/job-growth-sputters-rate-cuts-and-recession-incoming/',
 'https://www.etfdailynews.com/2025/09/07/nvidias-nvda-overweight-rating-reiterated-at-jpmorgan-chase-co/',
 'https://www.etfdailynews.com/2025/09/07/nvidia-corporation-nvda-is-nutshell-asset-management-ltds-10th-largest-position/',
 'https://www.etfdailynews.com/2025/09/07/wealthplan-partners-llc-purchases-13995-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/07/potentia-wealth-boosts-stake-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/07/nvidia-corporation-nvda-shares-sold-by-jackson-square-partners-llc/',
 'https://www.etfdailynews.com/2025/09/07/nvidia-corporation-nvda-stock-position-decreased-by-maryland-state-retirement-pension-system/',
 'https://www.etfdailynews.com/2025/09/07/nvidia-corporation-nvda-shares-purchased-by-fayez-sarofim-co/',
 'https://www.etfdailynews.com/2025/09/07/wealthplan-investment-management-llc-has-11-93-million-stock-holdings-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/07/alesco-advisors-llc-increases-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/07/y-d-more-investments-ltd-sells-7936-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/07/technology-stocks-to-watch-today-september-5th/',
 'https://www.etfdailynews.com/2025/09/07/nvidia-nasdaqnvda-upgraded-at-wall-street-zen/',
 'https://www.etfdailynews.com/2025/09/07/nvidia-nasdaqnvda-trading-down-3-9-following-insider-selling/',
 'https://www.fool.com.au/2025/09/07/how-to-build-wealth-with-asx-etfs-and-never-pick-a-single-stock/',
 'https://biztoc.com/x/74a2ec1d818bffe6',
 'https://finance.yahoo.com/news/president-trump-could-ve-asked-155608603.html',
 'https://www.etfdailynews.com/2025/09/06/novus-advisors-llc-has-3-39-million-stock-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/microsoft-corporation-msft-shares-bought-by-quantum-financial-planning-services-inc/',
 'https://www.etfdailynews.com/2025/09/06/palisades-hudson-asset-management-l-p-sells-372-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/microsoft-corporation-msft-shares-sold-by-bank-of-nova-scotia-trust-co/',
 'https://www.etfdailynews.com/2025/09/06/pnc-financial-services-group-inc-decreases-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/oversea-chinese-banking-corp-ltd-sells-13165-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/mirabaud-cie-sa-raises-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/mitsubishi-ufj-trust-banking-corp-cuts-stock-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/r-squared-ltd-lowers-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/06/rep-cleo-fields-buys-microsoft-corporation-nasdaqmsft-stock-3/',
 'https://applech2.com/archives/20250908-cyberpunk-2077-ultimate-mac-sale.html',
 'https://applech2.com/archives/20250905-beelink-ex-mate-mini-a.html',
 'https://biztoc.com/x/639de1dac4c30216',
 'https://biztoc.com/x/e6259e0de070387a',
 'https://finance.yahoo.com/news/apple-launch-ai-powered-answer-135707085.html',
 'https://www.thestreet.com/investing/stocks/after-jobs-report-street-hopes-for-good-news-from-oracle-adobe-kroger',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-holdings-reduced-by-amf-tjanstepension-ab/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-shares-sold-by-wambolt-associates-llc/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-stock-position-trimmed-by-accuvest-global-advisors/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-stock-holdings-lessened-by-beam-wealth-advisors-inc/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-is-bristlecone-advisors-llcs-3rd-largest-position/',
 'https://www.etfdailynews.com/2025/09/07/flagship-wealth-advisors-llc-increases-stock-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/07/hirtle-callaghan-co-llc-sells-70981-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/07/evernest-financial-advisors-llc-sells-112895-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/07/wealthplan-partners-llc-cuts-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/07/northwest-quadrant-wealth-management-llc-reduces-stock-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-shares-sold-by-wittenberg-investment-management-inc/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-position-increased-by-mitsubishi-ufj-asset-management-co-ltd/',
 'https://www.etfdailynews.com/2025/09/07/one-degree-advisors-inc-increases-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/07/apple-inc-aapl-holdings-cut-by-ironwood-investment-counsel-llc/',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-drift-higher-as-wall-street-weighs-feds-next-move-232914987.html',
 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-drift-as-wall-street-braces-for-revision-to-jobs-data-232914335.html',
 'https://applech2.com/archives/20250909-belkin-boostcharge-pro-3-ports-70w.html',
 'https://applech2.com/archives/20250909-google-drive-114-ends-support-macos-11-big-sur.html',
 'https://biztoc.com/x/980e4c510f4a1bd3',
 'https://www.barchart.com/story/news/34666920/stocks-mostly-higher-on-fed-easing-prospects',
 'https://www.marketwatch.com/story/these-are-the-stock-market-trades-to-make-going-into-the-end-of-the-year-according-to-goldman-sachs-694bfedf',
 'https://finance.yahoo.com/video/inflation-watch-apple-event-p-131510114.html',
 'https://www.barchart.com/story/news/34660103/stocks-set-to-open-higher-as-fed-rate-cut-expectations-rise-u-s-inflation-data-awaited',
 'https://www.etfdailynews.com/2025/09/08/apple-inc-aapl-is-lcnb-corps-7th-largest-position/',
 'https://www.etfdailynews.com/2025/09/08/first-western-trust-bank-has-24-90-million-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/condor-capital-management-has-30-93-million-holdings-in-apple-inc-aapl/',
 'https://wccftech.com/apple-watch-ultra-3-support-5g-and-satellite-connectivity-thanks-to-mediatek-modems/',
 'https://www.etfdailynews.com/2025/09/08/riverpark-capital-management-llc-purchases-231-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/connor-clark-lunn-investment-management-ltd-acquires-110777-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/avant-capital-llc-has-1-06-million-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/founders-financial-alliance-llc-reduces-stock-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/fsa-wealth-partners-inc-invests-479000-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/truepoint-inc-purchases-6612-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/ardent-capital-management-inc-raises-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/integrity-financial-corp-wa-has-7-50-million-stock-position-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/brookmont-capital-management-has-214000-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/08/promising-technology-stocks-to-add-to-your-watchlist-september-6th/',
 'https://finance.yahoo.com/news/why-td-cowen-stays-bullish-040345920.html',
 'https://www.globenewswire.com/news-release/2025/09/06/3145618/1087/en/Pomerantz-Law-Firm-Announces-the-Filing-of-a-Class-Action-Against-Tesla-Inc-and-Certain-Officers-TSLA.html',
 'https://www.etfdailynews.com/2025/09/06/hightower-advisors-llc-makes-new-104000-investment-in-direxion-daily-tsla-bull-2x-shares-tsll/',
 'https://www.etfdailynews.com/2025/09/06/promising-electric-vehicle-stocks-to-watch-now-september-4th/',
 'https://biztoc.com/x/75129f9a0941420a',
 'https://finance.yahoo.com/news/nebius-signs-17-4-billion-211147146.html',
 'https://biztoc.com/x/509fef805ecb4df8',
 'https://www.barchart.com/story/news/34671143/nvidias-rally-is-facing-a-reality-check-should-you-buy-nvda-stock-despite-citis-target-price-cut',
 'https://finance.yahoo.com/news/palantir-stock-breakout-170900343.html',
 'https://finance.yahoo.com/news/live/stock-market-today-sp-500-rises-nasdaq-on-track-for-record-as-wall-street-looks-ahead-to-inflation-reality-check-170830778.html',
 'https://biztoc.com/x/57374d35224ac237',
 'https://economictimes.indiatimes.com/news/international/us/us-stock-market-surges-today-nasdaq-and-sp-500-hit-record-highs-dow-flat-wall-street-on-the-move-as-robinhood-and-applovin-stocks-soar/articleshow/123768912.cms',
 'https://finance.yahoo.com/news/jim-cramer-reveals-big-debate-152142815.html',
 'https://www.barchart.com/story/news/34668168/stocks-supported-by-hopes-of-fed-rate-cuts',
 'https://biztoc.com/x/3f873a54d800383e',
 'https://biztoc.com/x/b864544f67f45752',
 'https://finance.yahoo.com/news/alibaba-bytedance-others-remain-keen-142925517.html',
 'https://www.etfdailynews.com/2025/09/08/summit-financial-strategies-inc-decreases-stake-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/nvidia-corporation-nvda-shares-purchased-by-rezny-wealth-management-inc/',
 'https://www.etfdailynews.com/2025/09/08/forsta-ap-fonden-has-696-87-million-stake-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/bristlecone-advisors-llc-has-32-57-million-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/nvidia-corporation-nvda-is-ns-partners-ltds-2nd-largest-position/',
 'https://www.etfdailynews.com/2025/09/08/benjamin-edwards-inc-sells-157657-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/best-automotive-stocks-to-research-september-6th/',
 'https://www.etfdailynews.com/2025/09/08/manhattan-west-asset-management-llc-raises-stock-position-in-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/measured-wealth-private-client-group-llc-sells-1700-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/frank-rimerman-advisors-llc-sells-25907-shares-of-nvidia-corporation-nvda/',
 'https://www.etfdailynews.com/2025/09/08/analysts-set-nvidia-corporation-nasdaqnvda-pt-at-207-69/',
 'https://www.thestreet.com/economy/inflation-is-the-weeks-watchword',
 'https://mjtsai.com/blog/2025/09/08/android-tracking-switch-privacy-lawsuit/',
 'https://podcasts.apple.com/us/podcast/passing-go-sharing-data-google-avoids-breakup-but-must/id1401725029?i=1000725507217',
 'https://finance.yahoo.com/news/why-rocket-lab-rklb-stock-182639864.html',
 'https://finance.yahoo.com/news/why-soundhound-ai-soun-stock-182613993.html',
 'https://www.forbes.com/sites/greatspeculations/2025/09/08/buy-sell-or-hold-american-eagle-stock/',
 'https://biztoc.com/x/f641c289149dcfc7',
 'https://biztoc.com/x/a451abb732892338',
 'https://www.forbes.com/sites/greatspeculations/2025/09/08/how-will-synopsys-stock-react-to-its-upcoming-earnings/',
 'https://www.forbes.com/sites/greatspeculations/2025/09/08/does-shopify-stock-have-more-room-to-run/',
 'https://biztoc.com/x/fa8d651380664395',
 'https://finance.yahoo.com/news/why-analysts-see-more-upside-102140398.html',
 'https://www.etfdailynews.com/2025/09/06/apple-inc-aapl-shares-purchased-by-bank-of-nova-scotia-trust-co/',
 'https://www.etfdailynews.com/2025/09/06/apple-inc-aapl-shares-sold-by-cheviot-value-management-llc/',
 'https://www.etfdailynews.com/2025/09/06/beta-wealth-group-inc-has-4-33-million-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/06/apple-inc-aapl-is-delta-financial-group-inc-s-largest-position/',
 'https://www.etfdailynews.com/2025/09/06/lgt-capital-partners-ltd-trims-stock-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/06/apple-inc-aapl-stock-holdings-raised-by-jupiter-asset-management-ltd/',
 'https://www.etfdailynews.com/2025/09/06/apple-inc-aapl-stake-raised-by-westchester-capital-management-inc/',
 'https://www.etfdailynews.com/2025/09/06/aviso-wealth-management-sells-1184-shares-of-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/06/cumberland-partners-ltd-lowers-holdings-in-apple-inc-aapl/',
 'https://www.etfdailynews.com/2025/09/06/united-super-pty-ltd-in-its-capacity-as-trustee-for-the-construction-building-unions-superannuation-fund-has-112-42-million-stock-holdings-in-apple-inc-aapl/',
 'https://applech2.com/archives/20250906-belkin-ultracharge-pro-3-in-1-magnetic-charging-dock-with-qi2-25w.html',
 'https://www.etfdailynews.com/2025/09/06/apple-nasdaqaapl-price-target-raised-to-260-00/',
 'https://www.etfdailynews.com/2025/09/06/rep-cleo-fields-purchases-shares-of-apple-inc-nasdaqaapl/',
 'https://www.etfdailynews.com/2025/09/06/rep-cleo-fields-purchases-shares-of-apple-inc-nasdaqaapl-2/',
 'https://www.globenewswire.com/news-release/2025/09/08/3146456/3080/en/Lost-Money-on-Tesla-Inc-TSLA-Join-Class-Action-Suit-Seeking-Recovery-Contact-Levi-Korsinsky.html',
 'https://biztoc.com/x/6f2461e3d79ccc09',
 'https://www.thestreet.com/automotive/tesla-report-reveals-concerning-customer-behavior-',
 'https://biztoc.com/x/e620ca9ffa816d75',
 'https://biztoc.com/x/b3f54f787124bcf7',
 'https://biztoc.com/x/86669513beabac95',
 'https://biztoc.com/x/ff0640ebc0d139ac',
 'https://biztoc.com/x/698f0e05a229194f',
 'https://finance.yahoo.com/news/tesla-tsla-entry-india-sees-142931553.html',
 'http://electrek.co/2025/09/08/tesla-tsla-us-market-share-ev-market-drop-new-lows/',
 'https://biztoc.com/x/8c10aa4ae1b6e531',
 'https://economictimes.indiatimes.com/news/international/us/us-stock-futures-edge-higher-today-dow-sp-500-nasdaq-start-the-week-in-green-as-wall-street-bets-on-fed-cut-and-key-inflation-test/articleshow/123763670.cms',
 'https://www.etfdailynews.com/2025/09/08/tradr-2x-short-tsla-daily-etf-nasdaqtslq-short-interest-up-68-3-in-august/',
 'https://www.etfdailynews.com/2025/09/08/direxion-daily-tsla-bear-1x-shares-nasdaqtsls-short-interest-update/',
 'https://www.etfdailynews.com/2025/09/08/promising-energy-stocks-to-add-to-your-watchlist-september-6th/',
 'https://www.etfdailynews.com/2025/09/08/industrial-stocks-to-follow-now-september-6th/',
 'https://www.etfdailynews.com/2025/09/08/utility-stocks-to-keep-an-eye-on-september-6th/',
 'https://finance.yahoo.com/news/tesla-stock-nasdaq-tsla-faces-040724978.html',
 'https://biztoc.com/x/0c3779febcb9f201',
 'https://www.etfdailynews.com/2025/09/06/jpmorgan-chase-co-forecasts-strong-price-appreciation-for-alphabet-nasdaqgoog-stock/',
 'https://www.etfdailynews.com/2025/09/06/alphabet-nasdaqgoog-stock-acquired-rep-cleo-fields/',
 'https://biztoc.com/x/67cde0c3421df6f8',
 'https://finance.yahoo.com/news/tesla-tsla-uk-sales-grow-140818236.html',
 'https://biztoc.com/x/dc9b46cd0e41bc93',
 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_2d2b024f-927e-4e45-b490-fb5d68c8cd55',
 'https://www.etfdailynews.com/2025/09/07/wbh-advisory-inc-has-22-25-million-stake-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/07/microsoft-corporation-msft-is-amf-tjanstepension-abs-largest-position/',
 'https://www.etfdailynews.com/2025/09/07/wambolt-associates-llc-cuts-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/07/microsoft-corporation-msft-is-swiss-national-banks-3rd-largest-position/',
 'https://biztoc.com/x/90465c78f1530ddc',
 'https://www.etfdailynews.com/2025/09/07/cresta-advisors-ltd-increases-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/07/northwest-quadrant-wealth-management-llc-has-985000-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/07/microsoft-nasdaqmsft-shares-down-2-5-following-insider-selling/',
 'https://www.etfdailynews.com/2025/09/07/stock-traders-buy-large-volume-of-call-options-on-microsoft-nasdaqmsft/',
 'https://biztoc.com/x/3da3196480da973a',
 'https://biztoc.com/x/ef03408de9947638',
 'https://www.etfdailynews.com/2025/09/08/koss-olinger-consulting-llc-increases-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/cynosure-group-llc-has-3-42-million-stock-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/zions-bancorporation-national-association-ut-invests-29-88-million-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-stake-cut-by-summit-financial-strategies-inc/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-shares-bought-by-rezny-wealth-management-inc/',
 'https://www.etfdailynews.com/2025/09/08/everett-harris-co-ca-has-565-11-million-position-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/nicholson-wealth-management-group-llc-raises-holdings-in-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/townsquare-capital-llc-buys-12649-shares-of-microsoft-corporation-msft/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-holdings-lowered-by-nbw-capital-llc/',
 'https://www.etfdailynews.com/2025/09/08/microsoft-corporation-msft-is-locust-wood-capital-advisers-llcs-2nd-largest-position/']

seen = set()
unique_urls = []
for u in urls:
    if u not in seen:
        seen.add(u)
        unique_urls.append(u)

summaries = []

for url in unique_urls: 
    try: 
        news = Article(url)
        news.download()
        news.parse()
        news.nlp()
        if news.summary:
             summaries.append(news.summary)
    except Exception as e: #add exemption for urls that get bad 401 error 
        print(f"Error processing url {url} {e}")

out_path = "news_summmary.txt"
with open(out_path, "w", encoding="utf-8") as f:
    for s in summaries:
        f.write(s.replace("\n", " ") + "\n")

print(f"wrote {len(summaries)} summaries to {out_path}")



         